kind: Template
apiVersion: v1
metadata:
  name: launchpad-missioncontrol
  annotations:
    openshift.io/display-name: "Launchpad - Mission Control"
    description: This application contains the Mission Control service
    tags: instant-app,launchpad
    iconClass: icon-shadowman
    template.openshift.io/long-description: This application contains the Mission Control service
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://github.com/openshiftio/launchpad-missioncontrol
    template.openshift.io/support-url: https://access.redhat.com
message: "The following service has been created in your project: mission-control.\n\nFor more information about using this template, including OpenShift considerations, see https://github.com/openshiftio"
labels:
  template: launchpad-missioncontrol
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: launchpad-missioncontrol
  spec:
    replicas: 1
    selector:
      deploymentconfig: launchpad-missioncontrol
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: launchpad-missioncontrol
      spec:
        containers:
        - env:
          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_API_URL
            valueFrom:
              configMapKeyRef:
                name: launchpad
                key: launchpad.missioncontrol.openshift.api.url
          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL
            valueFrom:
              configMapKeyRef:
                name: launchpad
                key: launchpad.missioncontrol.openshift.console.url
          - name: LAUNCHPAD_MISSIONCONTROL_GITHUB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: launchpad
                key: launchpad.missioncontrol.github.username
          - name: LAUNCHPAD_MISSIONCONTROL_GITHUB_TOKEN
            valueFrom:
              configMapKeyRef:
                name: launchpad
                key: launchpad.missioncontrol.github.token
          - name: LAUNCHPAD_KEYCLOAK_URL
            valueFrom:
              configMapKeyRef:
                name: launchpad
                key: launchpad.keycloak.url
          - name: LAUNCHPAD_KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: launchpad
                key: launchpad.keycloak.realm
          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: launchpad
                key: launchpad.missioncontrol.openshift.username
          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: launchpad
                key: launchpad.missioncontrol.openshift.password
          - name: LAUNCHPAD_TRACKER_SEGMENT_TOKEN
            valueFrom:
              configMapKeyRef:
                name: launchpad
                key: launchpad.tracker.segment.token
          image: launchpad-missioncontrol
          imagePullPolicy: Always
          name: launchpad-missioncontrol
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /api/health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange 
      imageChangeParams:
        automatic: true
        containerNames:
          - launchpad-missioncontrol
        from:
          kind: ImageStreamTag
          name: launchpad-missioncontrol:latest
- kind: Service
  apiVersion: v1
  metadata:
    name: launchpad-missioncontrol
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: launchpad-missioncontrol
    sessionAffinity: None
    type: ClusterIP
- kind: Route
  apiVersion: v1
  metadata:
    name: launchpad-missioncontrol
  spec:
    to:
      kind: Service
      name: launchpad-missioncontrol
